language: java
jdk: oraclejdk8
dist: trusty
install: true
script: mvn clean install

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - mvn clean test jacoco:report coveralls:report